### ISSUE TITLE
[BUG] Validation for yaml agent building

### ISSUE THREAD

**Issue by vizsatiz** [rootflo/flo-ai#5]
**Describe the bug**
Currently the yaml is directly compiled and executed for agentic flows. Instead add validations so that users can understand the problem with their yamls before execution

**To Reproduce**
1. Create a invalid yaml for example:

```yaml
apiVersion: flo/alpha-v1
kind: **InValidKind**
name: banking-assistant
agent:
    name: HousingLoanTeamLead
    role: Housing Loan Specialist
    job: Fetch the housing loan information from the db and answer the question
    tools:
      - name: HousingLoanTool
```
2. Try to build an execute

**Expected behavior**
A clear error about what is supported and what is not, and what should be fixed in the yaml

eg: "Unsupported flo.kind: InValidKind"
